trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '.infrastructure/*'
    exclude:
    - '*'

pr:
 branches:
   include:
   - master
 paths:
  include:
    - '.infrastructure/*'
  exclude:
   - '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'